export enum Meeting {
    MEETING_READ_SUCCESS = 'MEETING_READ_SUCCESS',
    MEETING_CREATED_SUCCESS = 'MEETING_CREATED_SUCCESS',
    MEETING_UPDATED_SUCCESS = 'MEETING_UPDATED_SUCCESS',
    MEETING_DELETED_SUCCESS = 'MEETING_DELETED_SUCCESS',
    MEETING_FAIL = 'MEETING_FAIL',
}
